In [1195]:
import pandas as pd
import re
import numpy as np

def load(file_name):
    df_test = pd.read_csv(file_name)
    sLength = len(df_test['id'])
    df_test.replace(regex={'<.*?>|&nbsp|\W': ' '}, inplace=True)
    df_test = df_test.fillna("missing")
    df_test['name'] = df_test['name'].str.lower()
    df_test['lvl1'] = df_test['lvl1'].str.lower()
    df_test['lvl2'] = df_test['lvl2'].str.lower()
    df_test['lvl3'] = df_test['lvl3'].str.lower()
    df_test['descrption'] = df_test['descrption'].str.lower()
    df_test['type'] = df_test['type'].str.lower()
    df_test['score'] = pd.Series(np.zeros(sLength, dtype=np.int), index=df_test.index)
    return df_test

def loadY(file_name):
    df = pd.read_csv(file_name)
    return df

def loadX(file_name):
    df_train = pd.read_csv(file_name)
    df_label = pd.read_csv('/Users/eashan22/Desktop/DataMining/FinalProject/project/data/train_label.csv')
    df_train = df_train.set_index('id').join(df_label.set_index('id'), how='inner')
    df_train.replace(regex={'<.*?>|&nbsp|\W': ' '}, inplace=True)
    df_train['name'] = df_train['name'].str.lower()
    df_train['lvl1'] = df_train['lvl1'].str.lower()
    df_train['lvl2'] = df_train['lvl2'].str.lower()
    df_train['lvl3'] = df_train['lvl3'].str.lower()
    df_train['descrption'] = df_train['descrption'].str.lower()
    df_train['type'] = df_train['type'].str.lower()
    df_train = df_train.fillna("missing")

    # df.dropna(inplace=True)
    # df['score'] = pd.Series(df_label['score'], index=df.index)
    return df_train

In [1196]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
import numpy as np
import pandas as pd

X_train =loadX('/Users/eashan22/Desktop/DataMining/FinalProject/project/data/train_data.csv')
X_test = load('/Users/eashan22/Desktop/DataMining/FinalProject/project/data/test_data.csv')

df_train = pd.DataFrame(data=X_train['lvl1']+X_train['lvl2']+X_train['lvl3']+X_train['type']+X_train['name']+X_train['descrption'],columns=['train'])

X_train_text = df_train.train
print(X_train_text.values)
# print(df_train['lvl1'].shape)

['health   beautybath   bodyhand   foot careinternationalcuba heartbreaker eau de parfum spray 100ml 3 3ozformulated with oil free hydrating botanicals  remarkably improves skin texture of abused hands restores soft  smooth   refined hands'
 'computers   laptopsstorageflash drivesinternational32gb usb 3 0 swivel flash drive memory stick storage thumb foldable pen red   interface  usb 3 0   capacity  32gb   material  abs plastic   fast data transfer rate  read  70mb sec  amp  write  30mb sec   compatible with usb 1 1 2 0   compatible with pc  notebook  mac    '
 'mobiles   tabletsaccessoriesphone casesinternationaleican alp8l 01 metal   pc phone cover luxury aluminum frame acrylic panel hard back case for huawei p8 lite mobile phone black    aluminum frame   built in stand   shockproof   snap on off installation   push pull design easy to fit    '
 ...
 'mobiles   tabletsaccessoriesphone casesinternationalmotomo wiredrawing pattern plastic case for iphone 6   6s 4 7  dark blue  export  

In [1197]:
df_test = pd.DataFrame(data=X_test['name']+X_test['lvl1']+X_test['lvl2']+X_test['lvl3']+X_test['type']+X_test['descrption'],columns=['test'])
X_test_text = df_test.test
# print(X_test_text.values)
print(X_test_text.shape)

(18142,)


In [1198]:
# tokenizer = Tokenizer(num_words=20000)
# tokenizer.fit_on_texts(X_train_text)
# X_train_des = X_train.descrption
# X_train_des = tokenizer.texts_to_sequences(X_train_des)
# X_train_des = pad_sequences(X_train_des,maxlen=16)
# df_train_des = pd.DataFrame(data=X_train_des)

# X_train_name = X_train.name
# X_train_name = tokenizer.texts_to_sequences(X_train_name)
# X_train_name = pad_sequences(X_train_name, maxlen=16)
# df_train_name = pd.DataFrame(data=X_train_name)

# X_train_lvl1 = X_train.lvl1
# X_train_lvl1 = tokenizer.texts_to_sequences(X_train_lvl1)
# X_train_lvl1 = pad_sequences(X_train_lvl1, maxlen=4)
# df_train_lvl1 = pd.DataFrame(data=X_train_lvl1)

# X_train_lvl2 = X_train.lvl2
# X_train_lvl2 = tokenizer.texts_to_sequences(X_train_lvl2)
# X_train_lvl2 = pad_sequences(X_train_lvl2, maxlen=4)
# df_train_lvl2 = pd.DataFrame(data=X_train_lvl2)

# X_train_lvl3 = X_train.lvl3
# X_train_lvl3 = tokenizer.texts_to_sequences(X_train_lvl3)
# X_train_lvl3 = pad_sequences(X_train_lvl3, maxlen=4)
# df_train_lvl3 = pd.DataFrame(data=X_train_lvl3)

# X_train_type = X_train.type
# X_train_type = tokenizer.texts_to_sequences(X_train_type)
# X_train_type = pad_sequences(X_train_type, maxlen=4)
# df_train_type = pd.DataFrame(data=X_train_type)

# frames = [df_train_lvl1,df_train_lvl2,df_train_lvl3,df_train_name,df_train_des,df_train_type]
# df_train = pd.concat(frames, axis=1)

# print(df_train.values)
# print(df_train.shape)

In [1199]:
# df_test = pd.DataFrame(data=X_test['name']+X_test['descrption']+X_test['lvl1']+X_test['lvl2']+X_test['lvl3']+X_test['type'],columns=['test'])
# X_test_text = df_test.test
# tokenizer.fit_on_texts(X_test_text)

# X_test_des = X_test.descrption
# X_test_des = tokenizer.texts_to_sequences(X_test_des)
# X_test_des = pad_sequences(X_test_des,maxlen = 16)
# df_test_des = pd.DataFrame(data=X_test_des)

# X_test_name = X_test.name
# X_test_name = tokenizer.texts_to_sequences(X_test_name)
# X_test_name = pad_sequences(X_test_name,maxlen = 16)
# df_test_name = pd.DataFrame(data=X_test_name)

# X_test_lvl1 = X_test.lvl1
# X_test_lvl1 = tokenizer.texts_to_sequences(X_test_lvl1)
# X_test_lvl1 = pad_sequences(X_test_lvl1, maxlen=4)
# df_test_lvl1 = pd.DataFrame(data=X_test_lvl1)

# X_test_lvl2 = X_test.lvl2
# X_test_lvl2 = tokenizer.texts_to_sequences(X_test_lvl2)
# X_test_lvl2 = pad_sequences(X_test_lvl2, maxlen=4)
# df_test_lvl2 = pd.DataFrame(data=X_test_lvl2)

# X_test_lvl3 = X_test.lvl3
# X_test_lvl3 = tokenizer.texts_to_sequences(X_test_lvl3)
# X_test_lvl3 = pad_sequences(X_test_lvl3, maxlen=4)
# df_test_lvl3 = pd.DataFrame(data=X_test_lvl3)

# X_test_type = X_test.type
# X_test_type = tokenizer.texts_to_sequences(X_test_type)
# X_test_type = pad_sequences(X_test_type, maxlen=4)
# df_test_type = pd.DataFrame(data=X_test_type)

# frames = [df_test_lvl1,df_test_lvl2,df_test_lvl3,df_test_name,df_test_des,df_test_type]
# df_test = pd.concat(frames,axis=1)

# print(df_test.values)
# print(df_test.shape)

In [1215]:
tokenizer = Tokenizer(num_words=20000)
tokenizer.fit_on_texts(X_train_text)

X_train_hh = tokenizer.texts_to_sequences(X_train_text)
X_train_hh = pad_sequences(X_train_hh,maxlen=243)
print(X_train_hh)
print(X_train_hh.shape)

[[   0    0    0 ...  278 2329  625]
 [   0    0    0 ...  126  637  641]
 [   0    0    0 ...   25    3  125]
 ...
 [   0    0    0 ...  440    1  405]
 [   0    0    0 ...  125   14   23]
 [   0    0    0 ...  425   35   47]]
(18141, 243)


In [1216]:
X_test_hh = tokenizer.texts_to_sequences(X_test_text)
X_test_hh = pad_sequences(X_test_hh,maxlen=243)
print(X_test_hh)
print(X_test_hh.shape)

[[   0    0    0 ...    5 2238 4120]
 [   0    0    0 ...   73  326 1181]
 [   0    0    0 ...   45   14  388]
 ...
 [   0    0    0 ...  812  589 3544]
 [   0    0    0 ... 1971    1 3871]
 [   0    0    0 ...   29 1976  956]]
(18142, 243)


In [1217]:
y_score = X_train.score.values
print(y_score)
print(y_score.shape)

[1 1 1 ... 1 0 1]
(18141,)


In [1218]:
import keras
import tensorflow as tf

model = keras.Sequential()
model.add(keras.layers.Embedding(20000, 18))

model.add(keras.layers.GlobalAveragePooling1D())
model.add(keras.layers.Dense(30, activation=tf.nn.relu))
model.add(keras.layers.Dropout(rate=0.5))
model.add(keras.layers.Dense(1, activation=tf.nn.sigmoid))

model.compile(optimizer=tf.train.AdamOptimizer(),
              loss='binary_crossentropy',
              metrics=['accuracy'])


model.fit(X_train_hh[2001:],y_score[2001:],
          epochs=13,
          batch_size=192,
          validation_data=(X_train_hh[0:2000], X_train[0:2000].score.values),
          verbose=1)

output_array = model.predict(X_test_hh)


print(output_array)



Train on 16140 samples, validate on 2000 samples
Epoch 1/13
16140/16140 [==============================] - 5s 327us/step - loss: 0.6528 - acc: 0.6866 - val_loss: 0.6279 - val_acc: 0.6755
Epoch 2/13
16140/16140 [==============================] - 0s 31us/step - loss: 0.6192 - acc: 0.6897 - val_loss: 0.6217 - val_acc: 0.6755
Epoch 3/13
16140/16140 [==============================] - 0s 30us/step - loss: 0.6129 - acc: 0.6897 - val_loss: 0.6117 - val_acc: 0.6750
Epoch 4/13
16140/16140 [==============================] - 0s 31us/step - loss: 0.5970 - acc: 0.6928 - val_loss: 0.5892 - val_acc: 0.6780
Epoch 5/13
16140/16140 [==============================] - 0s 31us/step - loss: 0.5654 - acc: 0.7133 - val_loss: 0.5582 - val_acc: 0.7200
Epoch 6/13
16140/16140 [==============================] - 1s 31us/step - loss: 0.5326 - acc: 0.7454 - val_loss: 0.5327 - val_acc: 0.7240
Epoch 7/13
16140/16140 [==============================] - 1s 31us/step - loss: 0.5059 - acc: 0.7574 - val_loss: 0.5149 - val_acc

In [1204]:
df_end_id = pd.DataFrame(data=X_test.id)
# print(X_test.id)

In [1205]:

df_end_score = pd.DataFrame(data=output_array,columns=['score'])
df_frames = [df_end_id,df_end_score]
df_end = pd.concat(df_frames,axis=1)

df_end.to_csv('/Users/eashan22/Desktop/DataMining/FinalProject/project/data/output7.csv',index=False)
print(df_end)
print(df_end.shape)

          id     score
0      18142  0.903027
1      18143  0.867133
2      18144  0.528902
3      18145  0.943663
4      18146  0.910467
5      18147  0.844827
6      18148  0.240060
7      18149  0.913365
8      18150  0.865241
9      18151  0.772387
10     18152  0.910509
11     18153  0.360984
12     18154  0.955943
13     18155  0.588503
14     18156  0.932398
15     18157  0.127000
16     18158  0.814373
17     18159  0.483881
18     18160  0.921859
19     18161  0.396744
20     18162  0.994675
21     18163  0.609777
22     18164  0.934683
23     18165  0.817683
24     18166  0.958504
25     18167  0.755571
26     18168  0.867065
27     18169  0.937922
28     18170  0.680023
29     18171  0.970930
...      ...       ...
18112  36254  0.918440
18113  36255  0.541725
18114  36256  0.929651
18115  36257  0.713764
18116  36258  0.202769
18117  36259  0.196672
18118  36260  0.852211
18119  36261  0.064765
18120  36262  0.550650
18121  36263  0.783211
18122  36264  0.108567
18123  3626